version: '3.8'
services:
  db:
    image: mysql:latest
    #    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'database'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'student'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      # ensure that you create the data folder in same directory as this file
      - ./data:/var/lib/mysql
